import { ContainerSidecarStatus } from "../types";

export function buildContainerSidecarReport(status: ContainerSidecarStatus): string {
  const lines = [
    "### Container Sidecar",
    "",
    `* sidecar intent detected: ${status.intentDetected ? "yes" : "no"}`,
    `* sidecar enabled: ${status.sidecarEnabled === undefined ? "unknown" : status.sidecarEnabled ? "yes" : "no"}`,
    `* sidecar reachable: ${status.sidecarReachable === undefined ? "unknown" : status.sidecarReachable ? "yes" : "no"}`,
    `* endpoint used: ${status.endpointUsed || "none"}`,
    `* local-only: ${status.localOnly ? "yes" : "no"}`,
    `* cloud fallback used: ${status.cloudFallbackUsed ? "yes" : "no"}`,
    `* model/provider used: ${status.modelProviderUsed || "unknown"}`,
    `* harmless prompt result: ${status.harmlessPromptResult || "not_run"}`,
    `* writes: ${status.writes || "no"}`,
    `* commit/push/Docker/external: ${status.commitPushDockerExternal || "no"}`,
    `* blocker if any: ${status.blocker || status.health.blocker || "none"}`,
    `* configured containerSidecar.enabled: ${status.configuredContainerSidecarEnabled === undefined ? "unknown" : status.configuredContainerSidecarEnabled ? "yes" : "no"}`,
    `* configured chatBaseUrl: ${status.configuredChatBaseUrl || "unknown"}`,
    `* configured openAiBaseUrl: ${status.configuredOpenAiBaseUrl || "unknown"}`,
    `* configured timeoutMs: ${status.configuredTimeoutMs === undefined ? "unknown" : String(status.configuredTimeoutMs)}`,
    `* config source assumption: ${status.configSourceAssumption || 'vscode.workspace.getConfiguration("ayla")'}`,
    `* extension version: ${status.extensionVersion || "unknown"}`,
    `* provider path: ${status.providerPath}`,
    `* request mode: ${status.requestMode}`,
    `* chat endpoint: ${status.chatEndpoint}`,
    `* openai endpoint: ${status.openAiEndpoint}`,
    `* traces endpoint: ${status.tracesEndpoint}`,
    `* safety allowed: ${status.safety.allowed ? "yes" : "no"}`,
    `* safety reason: ${status.safety.reason}`,
    `* write scope: ${status.writeScope || "none"}`,
    `* health reachable: ${status.health.reachable ? "yes" : "no"}`,
    `* health chat reachable: ${status.health.chatReachable ? "yes" : "no"}`,
    `* health openai reachable: ${status.health.openAiReachable ? "yes" : "no"}`,
    `* health traces reachable: ${status.health.tracesReachable ? "yes" : "no"}`,
    `* health blocker: ${status.health.blocker || "none"}`
  ];
  return lines.join("\n");
}

export function buildContainerSidecarExecutionProofReport(status: ContainerSidecarStatus): string {
  const structuredProof = Boolean(status.validationCommand || (status.proposedFiles?.length ?? 0) > 0);
  const lines = [
    status.previousProofFilePath ? "### Previous Proof Cleanup" : undefined,
    status.previousProofFilePath ? "" : undefined,
    status.previousProofFilePath ? `* previous proof file path: ${status.previousProofFilePath}` : undefined,
    status.previousProofFilePath ? `* previous proof file existed: ${status.previousProofFileExisted ? "yes" : "no"}` : undefined,
    status.previousProofFilePath ? `* previous proof file removed: ${status.previousProofFileRemoved ? "yes" : "no"}` : undefined,
    status.previousProofFilePath ? `* cleanup verified: ${status.cleanupVerified ? "yes" : "no"}` : undefined,
    status.previousProofFilePath ? `* cleanup scope: ${status.cleanupScope || "unknown"}` : undefined,
    status.previousProofFilePath ? `* cleanup blocker if any: ${status.cleanupBlocker || "none"}` : undefined,
    status.previousProofFilePath ? "" : undefined,
    structuredProof ? "### Container Sidecar Structured Edit Proof" : "### Container Sidecar Execution Proof",
    "",
    `* sidecar intent detected: ${status.intentDetected ? "yes" : "no"}`,
    `* sidecar enabled: ${status.sidecarEnabled === undefined ? "unknown" : status.sidecarEnabled ? "yes" : "no"}`,
    `* sidecar reachable: ${status.sidecarReachable === undefined ? "unknown" : status.sidecarReachable ? "yes" : "no"}`,
    `* endpoint used: ${status.endpointUsed || "none"}`,
    `* local-only: ${status.localOnly ? "yes" : "no"}`,
    `* cloud fallback used: ${status.cloudFallbackUsed ? "yes" : "no"}`,
    `* allowed write scope: ${status.allowedWriteScope || "none"}`,
    `* files requested: ${status.filesRequested?.join(", ") || "none"}`,
    `* sidecar reported write: ${status.sidecarReportedWrite ? "yes" : "no"}`,
    `* sidecar-reported files written: ${status.sidecarReportedFiles?.join(", ") || "none"}`,
    `* sidecar proposed write extracted: ${status.sidecarProposedWriteExtracted ? "yes" : "no"}`,
    `* proposal fallback endpoint attempted: ${status.proposalFallbackEndpointAttempted ? "yes" : "no"}`,
    `* proposal retry used: ${status.proposalRetryUsed ? "yes" : "no"}`,
    status.proposalRetryEndpoint ? `* proposal retry endpoint: ${status.proposalRetryEndpoint}` : undefined,
    typeof status.proposalRawResponseLength === "number" ? `* proposal response length: ${status.proposalRawResponseLength}` : undefined,
    status.proposalRawResponseSnippet ? `* raw sidecar response snippet: ${status.proposalRawResponseSnippet}` : undefined,
    status.proposalRawResponseTail ? `* raw sidecar response tail: ${status.proposalRawResponseTail}` : undefined,
    typeof status.proposalLookedFencedJson === "boolean" ? `* proposal looked fenced json: ${status.proposalLookedFencedJson ? "yes" : "no"}` : undefined,
    status.proposalExtractionFailureReason ? `* proposal extraction failure reason: ${status.proposalExtractionFailureReason}` : undefined,
    status.proposalFirstFailureReason ? `* proposal first failure reason: ${status.proposalFirstFailureReason}` : undefined,
    status.proposalRetryFailureReason ? `* proposal retry failure reason: ${status.proposalRetryFailureReason}` : undefined,
    status.proposalExpectedSchema ? `* expected schema: ${status.proposalExpectedSchema}` : undefined,
    typeof status.proposalOutputBudget === "number" ? `* proposal output budget: ${status.proposalOutputBudget}` : undefined,
    `* host bridge write applied: ${status.hostBridgeWriteApplied ? "yes" : "no"}`,
    `* host readback checked: ${status.hostReadbackChecked ? "yes" : "no"}`,
    `* host file path: ${status.hostFilePath || "none"}`,
    `* host file exists: ${status.hostFileExists === undefined ? "unknown" : status.hostFileExists ? "yes" : "no"}`,
    `* host content matches: ${status.hostContentMatches === undefined ? "unknown" : status.hostContentMatches ? "yes" : "no"}`,
    `* sidecar proof verified: ${status.sidecarProofVerified ? "yes" : "no"}`,
    `* bridge mode used: ${status.bridgeModeUsed ? "yes" : "no"}`,
    `* proposed files: ${status.proposedFiles?.join(", ") || "none"}`,
    `* files written: ${status.filesWritten?.join(", ") || "none"}`,
    `* host-verified files: ${status.hostVerifiedFiles?.join(", ") || "none"}`,
    `* validation command: ${status.validationCommand || "none"}`,
    `* validation result: ${status.validationResult || "none"}`,
    `* validation passed: ${status.validationPassed ? "yes" : "no"}`,
    `* writes outside scope: ${status.writesOutsideScope || "unknown"}`,
    `* commit/push/Docker/external: ${status.commitPushDockerExternal || "no"}`,
    `* trace available: ${status.traceAvailable || "no"}`,
    `* proof result: ${status.proofResult || "unknown"}`,
    `* blocker if any: ${status.blocker || status.health.blocker || "none"}`,
    `* configured containerSidecar.enabled: ${status.configuredContainerSidecarEnabled === undefined ? "unknown" : status.configuredContainerSidecarEnabled ? "yes" : "no"}`,
    `* configured chatBaseUrl: ${status.configuredChatBaseUrl || "unknown"}`,
    `* configured openAiBaseUrl: ${status.configuredOpenAiBaseUrl || "unknown"}`,
    `* configured timeoutMs: ${status.configuredTimeoutMs === undefined ? "unknown" : String(status.configuredTimeoutMs)}`,
    `* config source assumption: ${status.configSourceAssumption || 'vscode.workspace.getConfiguration("ayla")'}`,
    `* extension version: ${status.extensionVersion || "unknown"}`,
    `* provider path: ${status.providerPath}`,
    `* request mode: ${status.requestMode}`,
    `* chat endpoint: ${status.chatEndpoint}`,
    `* openai endpoint: ${status.openAiEndpoint}`,
    `* traces endpoint: ${status.tracesEndpoint}`,
    `* safety allowed: ${status.safety.allowed ? "yes" : "no"}`,
    `* safety reason: ${status.safety.reason}`,
    `* write scope: ${status.writeScope || "none"}`,
    `* health reachable: ${status.health.reachable ? "yes" : "no"}`,
    `* health chat reachable: ${status.health.chatReachable ? "yes" : "no"}`,
    `* health openai reachable: ${status.health.openAiReachable ? "yes" : "no"}`,
    `* health traces reachable: ${status.health.tracesReachable ? "yes" : "no"}`,
    `* health blocker: ${status.health.blocker || "none"}`
  ];
  return lines.join("\n");
}
